import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNewColumn1786112250137 implements MigrationInterface {
    name = 'AddNewColumn1786112250137'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "menu_items" DROP CONSTRAINT "FK_menu_items_restaurant"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_menu_item"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_order"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_agent"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_customer"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_restaurant"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_customer"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_order"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_restaurant"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP CONSTRAINT "FK_restaurants_owner"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_refresh_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "notification_preferences_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_favorites_restaurant"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_favorites_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menu_items_restaurant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menu_items_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_restaurant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_placed_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_restaurant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_restaurants_owner_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_restaurants_cuisine_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_selector"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_isDeleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_preferences_userId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_favorites_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_favorites_restaurant_id"`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying, "action" character varying NOT NULL, "resource" character varying NOT NULL, "resourceId" character varying NOT NULL, "changes" json, "ipAddress" character varying, "userAgent" character varying, "requestId" character varying, "wasSuccessful" boolean NOT NULL DEFAULT false, "errorMessage" character varying, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5db7a2b9e2bd2563b2377c293c" ON "audit_logs" ("resource", "resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ee52ff271c0f9bca5f97daa0a" ON "audit_logs" ("userId", "action") `);
        await queryRunner.query(`CREATE TABLE "order_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" character varying NOT NULL, "deliveryAddress" character varying NOT NULL, "deliveryInstructions" character varying, "totalAmount" numeric(10,2) NOT NULL, "isComplete" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b6b9ed5fdd6411e9f9c1d727f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "UQ_6e71a912647d2d0cea5070cffbb" UNIQUE ("selector")`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "family"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "family" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "replacedByTokenId"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "replacedByTokenId" character varying`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "UQ_b70c44e8b00757584a393225593" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e71a912647d2d0cea5070cffb" ON "refresh_tokens" ("selector") `);
        await queryRunner.query(`CREATE INDEX "IDX_968936751ab847471635be8dc0" ON "refresh_tokens" ("family") `);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "FK_a8ff5699334d3ca7b07421af0a9" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_d8453d5a71e525d9b406c35aab8" FOREIGN KEY ("menuItemId") REFERENCES "menu_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_2312cd07a04f50ba29d76c9564e" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_98f71dbb92cea9a36e3a196f7b9" FOREIGN KEY ("agentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6d99bdfa69280ede313699fab92" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_92ad8cd051c76d10e284bbc3283" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_53a68dc905777554b7f702791fa" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD CONSTRAINT "FK_9519e81d388514ec631d23fefca" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_b70c44e8b00757584a393225593" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_e747534006c6e3c2f09939da60f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_05922e2bde7d7faf600bc586e84" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_05922e2bde7d7faf600bc586e84"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_e747534006c6e3c2f09939da60f"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_b70c44e8b00757584a393225593"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP CONSTRAINT "FK_9519e81d388514ec631d23fefca"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_53a68dc905777554b7f702791fa"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_92ad8cd051c76d10e284bbc3283"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6d99bdfa69280ede313699fab92"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_98f71dbb92cea9a36e3a196f7b9"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_2312cd07a04f50ba29d76c9564e"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_d8453d5a71e525d9b406c35aab8"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "menu_items" DROP CONSTRAINT "FK_a8ff5699334d3ca7b07421af0a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_968936751ab847471635be8dc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e71a912647d2d0cea5070cffb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "UQ_b70c44e8b00757584a393225593"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "replacedByTokenId"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "replacedByTokenId" uuid`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "family"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "family" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "UQ_6e71a912647d2d0cea5070cffbb"`);
        await queryRunner.query(`DROP TABLE "order_batches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ee52ff271c0f9bca5f97daa0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5db7a2b9e2bd2563b2377c293c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`CREATE INDEX "idx_favorites_restaurant_id" ON "favorites" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "idx_favorites_user_id" ON "favorites" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_preferences_userId" ON "notification_preferences" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_isDeleted" ON "users" ("isDeleted") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_refresh_tokens_selector" ON "refresh_tokens" ("selector") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_family" ON "refresh_tokens" ("family") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_userId" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_restaurants_cuisine_type" ON "restaurants" ("cuisineType") `);
        await queryRunner.query(`CREATE INDEX "idx_restaurants_owner_id" ON "restaurants" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_restaurant_id" ON "reviews" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_placed_at" ON "orders" ("placedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_restaurant_id" ON "orders" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_customer_id" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "idx_menu_items_category" ON "menu_items" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_menu_items_restaurant_id" ON "menu_items" ("restaurantId") `);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_refresh_tokens_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD CONSTRAINT "FK_restaurants_owner" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_customer" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_customer" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_agent" FOREIGN KEY ("agentId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_menu_item" FOREIGN KEY ("menuItemId") REFERENCES "menu_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "FK_menu_items_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
